### PR TITLE
Fixes issue with Guided Access or Single App modes  (rdar://40809553)

### LINKED ISSUE #365: Log in doesn't work in Guided Access or Single App modes
**Describe the bug**
Log in doesn't work in Guided Access mode or single app mode with supervised devices under an MDM. As per https://openradar.appspot.com/48376122, both ASWebAuthenticationSession and SFAuthenticationSession return an error (Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=1 "(null)") in these cases.

**To Reproduce**
1. Enable guided access on a device (Settings -> General -> Accessibility)
2. Set up and run the example project.
3. Start guided access mode on device (Tap home/power button 3 times, depending on device type)
4. Tap button "Authorize" in the app.

**Expected behavior**
Have an alert window to continue sign-in, and then the webview should appear.

** Actual behavior**
Neither the alert window nor the webview are presented, and an error occurs (Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=1 "(null)").

**Smartphone:**
 - Device: iPhone8
 - OS: iOS 12.1.4
 - XCode: 10.1 10B61

Tested with library versions 0.95.0 and master.

### PR DESCRIPTION
**Pull request by cassianodialpad**
Fixes #365

### CODE REVIEW

**Comment by WilliamDenniss** [comment]
I gather this fixes the issue by opening Safari?

Can you sign the [CLA ](https://openid.net/intellectual-property/contribution-license-agreement/)or link me to your one if you have already?

**Comment by cassianodialpad** [comment]
Yes, it will open Safari when in Guided Access.

My company has sent the corporate CLA to help@oidf.org , but it seems it has not been processed yet (Dialpad is not on the list).

**Comment by cassianodialpad** [comment]
Hi @WilliamDenniss , here is the CLA: https://openid.net/wordpress-content/uploads/2019/03/Dialpad-Inc_CLA-Agreement-Corporate_2019-03-18.pdf

File: Source/iOS/OIDExternalUserAgentIOS.m [hunk 1]
```diff
@@ -65,65 +65,75 @@ - (BOOL)presentExternalUserAgentRequest:(id<OIDExternalUserAgentRequest>)request
   NSURL *requestURL = [request externalUserAgentRequestURL];
 
   // iOS 12 and later, use ASWebAuthenticationSession
+  // ASWebAuthenticationSession doesn't work with guided access (rdar://40809553)
   if (@available(iOS 12.0, *)) {
```
Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: I would just add the extra condition here, i.e. `&& !UIAccessibilityIsGuidedAccessEnabled()` makes for less indentation.

File: Source/iOS/OIDExternalUserAgentIOS.m [hunk 2]
```diff
@@ -65,65 +65,75 @@ - (BOOL)presentExternalUserAgentRequest:(id<OIDExternalUserAgentRequest>)request
...
-                             underlyingError:error
-                                 description:@"User cancelled."];
-        [strongSelf->_session failExternalUserAgentFlowWithError:safariError];
-      }
-    }];
-    _authenticationVC = authenticationVC;
-    openedSafari = [authenticationVC start];
+  // SFAuthenticationSession doesn't work with guided access (rdar://40809553)
+  if (@available(iOS 11.0, *)) {
+    if (!openedSafari && !UIAccessibilityIsGuidedAccessEnabled()) {
```
Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: same comment as above for `&& !UIAccessibilityIsGuidedAccessEnabled()`.

Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: I don't see how `openedSafari` can ever be true at this point is that check needed?

File: Source/iOS/OIDExternalUserAgentIOS.m [hunk 3]
```diff
@@ -154,21 +164,17 @@ - (void)dismissExternalUserAgentAnimated:(BOOL)animated completion:(void (^)(voi
   
   [self cleanUp];
   
-  if (@available(iOS 12.0, *)) {
```
Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: I like the refactor of this whole section here.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 1 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Actually Xcode gives a compilation error when chaining conditions with `@available`, see https://stackoverflow.com/questions/46965347/objective-c-available-guard-anded-with-more-conditions.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Same.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 3 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Thanks. It actually wasn't just a refactor, but to prevent problems if the user switch on/off guided access in the middle of the login process.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: True, I will fix that.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 3 above)
Comment (WilliamDenniss) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Oh, not saying it wasn't needed - I just like this improvement even without the guided access fixes, I think it's the better way to structure it generally.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Actually it is needed in this context indeed: if on iOS12 not in access mode, `openedSafari` will have the result of `[authenticationVC start]`. If it did not work with ASWebAuthenticationSession for some reason, it will still try SFAuthenticationSession.
What do you think? Is there a better way to handle this?

Comment (WilliamDenniss) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Ah ok, I missed that the `else if` was removed.

The new logic is a little harder to read, but it's also inconsistent. In most places "openedSafari" is the test rather than the platform version, but in the case of mobile Safari there's no `openedSafari` check, and happens only for iOS 8 & below like before (mobile safari is opened in the `else` path of the iOS 9 version check).

I think we need to holistically look at the logic here and move to consistent model, not just apply a fix for UIAccessibilityIsGuidedAccessEnabled.

Perhaps that consistent model is "did the previous preferred method work, otherwise try the next best option", which is almost what you've done here, with the exception of mobile Safari.

File: Source/iOS/OIDExternalUserAgentIOS.m [hunk 4]
```diff
@@ -65,65 +65,75 @@ - (BOOL)presentExternalUserAgentRequest:(id<OIDExternalUserAgentRequest>)request
...
+        } else {
+          NSError *safariError =
+              [OIDErrorUtilities errorWithCode:OIDErrorCodeUserCanceledAuthorizationFlow
+                               underlyingError:error
+                                   description:nil];
+          [strongSelf->_session failExternalUserAgentFlowWithError:safariError];
+        }
+      }];
+      _webAuthenticationVC = authenticationVC;
+      openedSafari = [authenticationVC start];
```
Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: Can you rename `openedSafari` to `openedUserAgent` for accuracy?

Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Sure!

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Makes sense. I didn't want to modify the code too much for that fix, but you are right. I will make the changes.

Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: I added the condition on the `else` path. Do you think we need a larger refactor to this model?

File: Source/iOS/OIDExternalUserAgentIOS.m [hunk 5]
```diff
@@ -61,82 +61,93 @@ - (BOOL)presentExternalUserAgentRequest:(id<OIDExternalUserAgentRequest>)request
 
   _externalUserAgentFlowInProgress = YES;
   _session = session;
-  BOOL openedSafari = NO;
+  BOOL openedUserAgent = NO;
   NSURL *requestURL = [request externalUserAgentRequestURL];
 
   // iOS 12 and later, use ASWebAuthenticationSession
+  // ASWebAuthenticationSession doesn't work with guided access (rdar://40809553)
```
Comment (WilliamDenniss) [inline Source/iOS/OIDExternalUserAgentIOS.m]: Can you move this comment to just above the if-statement for `UIAccessibilityIsGuidedAccessEnabled`? And below

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (WilliamDenniss) [reply Source/iOS/OIDExternalUserAgentIOS.m]: I think it's good to go. The approach seems valid, it's basically a cascading order of preferences that's less attached to the iOS version now (while still gated by the version).

Comment (WilliamDenniss) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Can you address the nit regarding the comment, and squish the commits into 1?

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 5 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Sure.

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 2 above)
Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: You don't squash for merging pull requests?

File: Source/iOS/OIDExternalUserAgentIOS.m (hunk 5 above)
Comment (WilliamDenniss) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Sorry I just meant just the UIAccessibilityIsGuidedAccessEnabled comment, not both. I think the comment should precede the if-statement that it relates to.

Comment (cassianodialpad) [reply Source/iOS/OIDExternalUserAgentIOS.m]: Done! =)

**Comment by cassianodialpad** [comment]
Thanks!
How do I make a PR for a fix to the current version?

**Comment by WilliamDenniss** [comment]
Assuming no commits: stash any changes, checkout HEAD, pop the stash and continue.

**Comment by cassianodialpad** [comment]
Sorry, I did't get it... The current version is 0.95.0, is it possible to create a 0.95.1 with this fix? From what I understand from github, I can't make a PR to other branch than master (or to create a new one).

**Comment by WilliamDenniss** [comment]
I thought you were referring to further changes on this branch.

0.95.0 is a tag, we release it from the [pre1.0 ](https://github.com/openid/AppAuth-iOS/tree/pre1.0) branch which you can file a PR against, and we can cut a 0.95.1 from that.

Personally wouldn't bother backporting the fix though, anyone who needs this should just use the 1.x builds. We'll be cutting a release candidate from master soon.

**Comment by cassianodialpad** [comment]
I'm using https://github.com/google/GTMAppAuth, with depends on 0.95.0 and breaks with 1.0... =/
